# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_v4.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, pyqtSlot

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 560)
        Form.setMaximumSize(QtCore.QSize(1024, 600))
        font = QtGui.QFont()
        font.setPointSize(16)
        Form.setFont(font)
        Form.setStyleSheet("")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 50, 500, 190))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setStyleSheet("border-color: rgb(85, 85, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(3)
        self.frame.setObjectName("frame")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 500, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 50, 491, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_StartTour = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_StartTour.sizePolicy().hasHeightForWidth())
        self.pushButton_StartTour.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_StartTour.setFont(font)
        self.pushButton_StartTour.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushButton_StartTour.setFlat(False)
        self.pushButton_StartTour.setObjectName("pushButton_StartTour")
        self.horizontalLayout.addWidget(self.pushButton_StartTour)
        self.pushButton_EndTour = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_EndTour.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_EndTour.sizePolicy().hasHeightForWidth())
        self.pushButton_EndTour.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_EndTour.setFont(font)
        self.pushButton_EndTour.setStyleSheet("background-color: rgb(220, 73, 0);")
        self.pushButton_EndTour.setObjectName("pushButton_EndTour")
        self.horizontalLayout.addWidget(self.pushButton_EndTour)
        self.pushButton_pause = QtWidgets.QPushButton(self.frame)
        self.pushButton_pause.setEnabled(False)
        self.pushButton_pause.setGeometry(QtCore.QRect(80, 140, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_pause.setFont(font)
        self.pushButton_pause.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushButton_pause.setFlat(False)
        self.pushButton_pause.setObjectName("pushButton_pause")
        self.pushButton_resume = QtWidgets.QPushButton(self.frame)
        self.pushButton_resume.setEnabled(False)
        self.pushButton_resume.setGeometry(QtCore.QRect(260, 140, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_resume.setFont(font)
        self.pushButton_resume.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.pushButton_resume.setFlat(False)
        self.pushButton_resume.setObjectName("pushButton_resume")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(10, 250, 500, 221))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_GoGoal = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_GoGoal.setGeometry(QtCore.QRect(330, 50, 160, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_GoGoal.setFont(font)
        self.pushButton_GoGoal.setObjectName("pushButton_GoGoal")
        self.pushButton_CancelGoal = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_CancelGoal.setGeometry(QtCore.QRect(330, 120, 160, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_CancelGoal.setFont(font)
        self.pushButton_CancelGoal.setObjectName("pushButton_CancelGoal")
        self.comboBox_GoalSelect = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_GoalSelect.setGeometry(QtCore.QRect(10, 80, 301, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_GoalSelect.setFont(font)
        self.comboBox_GoalSelect.setEditable(False)
        self.comboBox_GoalSelect.setCurrentText("")
        self.comboBox_GoalSelect.setObjectName("comboBox_GoalSelect")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(0, 5, 500, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(520, 50, 500, 141))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("border-color: rgb(85, 85, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(3)
        self.frame_3.setObjectName("frame_3")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 500, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 40, 481, 98))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.layoutWidget1.setFont(font)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_currentGoal = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_currentGoal.setFont(font)
        self.label_currentGoal.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_currentGoal.setText("")
        self.label_currentGoal.setObjectName("label_currentGoal")
        self.gridLayout.addWidget(self.label_currentGoal, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_nextGoal = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_nextGoal.setFont(font)
        self.label_nextGoal.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_nextGoal.setText("")
        self.label_nextGoal.setObjectName("label_nextGoal")
        self.gridLayout.addWidget(self.label_nextGoal, 1, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(520, 190, 500, 331))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 500, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_CameraView = QtWidgets.QLabel(self.frame_4)
        self.label_CameraView.setGeometry(QtCore.QRect(39, 40, 441, 281))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_CameraView.setFont(font)
        self.label_CameraView.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label_CameraView.setAlignment(QtCore.Qt.AlignCenter)
        self.label_CameraView.setObjectName("label_CameraView")
        self.label_9.raise_()
        self.label_CameraView.raise_()
        self.splitter_3 = QtWidgets.QSplitter(Form)
        self.splitter_3.setGeometry(QtCore.QRect(0, 0, 0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.splitter_3.setFont(font)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_4 = QtWidgets.QSplitter(Form)
        self.splitter_4.setGeometry(QtCore.QRect(0, 0, 0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.splitter_4.setFont(font)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.progressBar_batteryStatus = QtWidgets.QProgressBar(Form)
        self.progressBar_batteryStatus.setGeometry(QtCore.QRect(870, 5, 150, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.progressBar_batteryStatus.setFont(font)
        self.progressBar_batteryStatus.setProperty("value", 72)
        self.progressBar_batteryStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_batteryStatus.setObjectName("progressBar_batteryStatus")
        self.label = QtWidgets.QLabel(Form)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(0, 0, 1024, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color: rgb(0, 170, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.label_statusbar = QtWidgets.QLabel(Form)
        self.label_statusbar.setGeometry(QtCore.QRect(5, 480, 520, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_statusbar.setFont(font)
        self.label_statusbar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_statusbar.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_statusbar.setObjectName("label_statusbar")
        self.pushButton_help = QtWidgets.QPushButton(Form)
        self.pushButton_help.setGeometry(QtCore.QRect(824, 520, 200, 40))
        self.pushButton_help.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_help.setFont(font)
        self.pushButton_help.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.pushButton_help.setObjectName("pushButton_help")

        self.retranslateUi(Form)
        self.pushButton_StartTour.clicked.connect(self.click_StartTour)
        self.pushButton_EndTour.clicked.connect(self.click_EndTour)
        self.pushButton_GoGoal.clicked.connect(self.click_Go)
        self.pushButton_CancelGoal.clicked.connect(self.click_Cancel)
        self.pushButton_help.clicked.connect(self.click_Help)
        self.comboBox_GoalSelect.activated['QString'].connect(self.onActivated)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_7.setText(_translate("Form", "Tour tự động"))
        self.pushButton_StartTour.setText(_translate("Form", "Bắt đầu"))
        self.pushButton_EndTour.setText(_translate("Form", "Kết thúc"))
        self.pushButton_pause.setText(_translate("Form", "Tạm dừng"))
        self.pushButton_resume.setText(_translate("Form", "Tiếp tục"))
        self.pushButton_GoGoal.setText(_translate("Form", "Đi"))
        self.pushButton_CancelGoal.setText(_translate("Form", "Hủy"))
        self.label_6.setText(_translate("Form", "Lựa chọn điểm đến"))
        self.label_8.setText(_translate("Form", "Thông tin"))
        self.label_3.setText(_translate("Form", "Điểm hiện tại:"))
        self.label_4.setText(_translate("Form", "Điểm tiếp theo:"))
        self.label_9.setText(_translate("Form", "Camera"))
        self.label_CameraView.setText(_translate("Form", "image camera"))
        self.label.setText(_translate("Form", "CMC-CIST SHOWROOM TOUR GUIDE"))
        self.label_statusbar.setText(_translate("Form", "Status bar..."))
        self.pushButton_help.setText(_translate("Form", "Hướng dẫn"))

    @pyqtSlot()
    def click_StartTour(self):
        pass 
    @pyqtSlot()
    def click_PauseTour(self):
        pass 
    @pyqtSlot()
    def click_ResumeTour(self):
        pass 
    @pyqtSlot()
    def click_EndTour(self):
        pass 
    @pyqtSlot()
    def click_Go(self):
        pass 
    @pyqtSlot()
    def click_Cancel(self):
        pass 
    @pyqtSlot()
    def click_Help(self):
        pass
    @pyqtSlot()
    def onActivated(self):
        pass

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

