# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_v3.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, pyqtSlot

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 600)
        Form.setMaximumSize(QtCore.QSize(1024, 600))
        Form.setStyleSheet("")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 50, 491, 121))
        self.frame.setStyleSheet("border-color: rgb(85, 85, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(3)
        self.frame.setObjectName("frame")
        # self.setWindowIcon(QtGui.QIcon(current_directory+"image/robot.ico"))
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 0, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_noticeTour = QtWidgets.QLabel(self.frame)
        self.label_noticeTour.setGeometry(QtCore.QRect(0, 89, 491, 31))
        self.label_noticeTour.setText("")
        self.label_noticeTour.setAlignment(QtCore.Qt.AlignCenter)
        self.label_noticeTour.setObjectName("label_noticeTour")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(0, 40, 491, 51))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_StartTour = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_StartTour.setFont(font)
        self.pushButton_StartTour.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushButton_StartTour.setFlat(False)
        self.pushButton_StartTour.setObjectName("pushButton_StartTour")
        self.horizontalLayout.addWidget(self.pushButton_StartTour)
        self.pushButton_PauseTour = QtWidgets.QPushButton(self.widget)
        self.pushButton_PauseTour.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_PauseTour.setFont(font)
        self.pushButton_PauseTour.setStyleSheet("background-color: rgb(220, 204, 0);")
        self.pushButton_PauseTour.setFlat(False)
        self.pushButton_PauseTour.setObjectName("pushButton_PauseTour")
        self.horizontalLayout.addWidget(self.pushButton_PauseTour)
        self.pushButton_ResumeTour = QtWidgets.QPushButton(self.widget)
        self.pushButton_ResumeTour.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_ResumeTour.setFont(font)
        self.pushButton_ResumeTour.setStyleSheet("background-color: rgb(0, 200, 100);") #(0, 204, 204)
        self.pushButton_ResumeTour.setFlat(False)
        self.pushButton_ResumeTour.setObjectName("pushButton_ResumeTour")
        self.horizontalLayout.addWidget(self.pushButton_ResumeTour)
        self.pushButton_EndTour = QtWidgets.QPushButton(self.widget)
        self.pushButton_EndTour.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_EndTour.setFont(font)
        self.pushButton_EndTour.setStyleSheet("background-color: rgb(220, 73, 0);")
        self.pushButton_EndTour.setObjectName("pushButton_EndTour")
        self.horizontalLayout.addWidget(self.pushButton_EndTour)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(10, 180, 491, 181))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_GoGoal = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_GoGoal.setGeometry(QtCore.QRect(320, 30, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_GoGoal.setFont(font)
        self.pushButton_GoGoal.setObjectName("pushButton_GoGoal")
        self.pushButton_CancelGoal = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_CancelGoal.setGeometry(QtCore.QRect(320, 80, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_CancelGoal.setFont(font)
        self.pushButton_CancelGoal.setObjectName("pushButton_CancelGoal")
        self.comboBox_GoalSelect = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_GoalSelect.setGeometry(QtCore.QRect(10, 50, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboBox_GoalSelect.setFont(font)
        self.comboBox_GoalSelect.setEditable(False)
        self.comboBox_GoalSelect.setObjectName("comboBox_GoalSelect")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(10, 0, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_GoalDetail = QtWidgets.QLabel(self.frame_2)
        self.label_GoalDetail.setGeometry(QtCore.QRect(10, 100, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_GoalDetail.setFont(font)
        self.label_GoalDetail.setStyleSheet("border-color: rgb(171, 171, 171);")
        self.label_GoalDetail.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_GoalDetail.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_GoalDetail.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_GoalDetail.setObjectName("label_GoalDetail")
        self.label_GoalDetail.setWordWrap(True)
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(520, 50, 491, 161))
        self.frame_3.setStyleSheet("border-color: rgb(85, 85, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(3)
        self.frame_3.setObjectName("frame_3")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(10, 0, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.layoutWidget = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 25, 481, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_currentGoal = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_currentGoal.setFont(font)
        self.label_currentGoal.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_currentGoal.setText("")
        self.label_currentGoal.setObjectName("label_currentGoal")
        self.gridLayout.addWidget(self.label_currentGoal, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_nextGoal = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_nextGoal.setFont(font)
        self.label_nextGoal.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_nextGoal.setText("")
        self.label_nextGoal.setObjectName("label_nextGoal")
        self.gridLayout.addWidget(self.label_nextGoal, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.progressBar_batteryStatus = QtWidgets.QProgressBar(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.progressBar_batteryStatus.setFont(font)
        self.progressBar_batteryStatus.setProperty("value", 72)
        self.progressBar_batteryStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_batteryStatus.setObjectName("progressBar_batteryStatus")
        self.gridLayout.addWidget(self.progressBar_batteryStatus, 2, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(520, 220, 491, 331))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(10, 0, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_CameraView = QtWidgets.QLabel(self.frame_4)
        self.label_CameraView.setGeometry(QtCore.QRect(39, 30, 441, 281))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_CameraView.setFont(font)
        self.label_CameraView.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label_CameraView.setAlignment(QtCore.Qt.AlignCenter)
        self.label_CameraView.setObjectName("label_CameraView")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(1, 8, 1041, 31))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color: rgb(0, 170, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.splitter)
        self.line.setMaximumSize(QtCore.QSize(1081, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setGeometry(QtCore.QRect(5, 570, 1019, 30))
        self.splitter_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_statusbar = QtWidgets.QLabel(self.splitter_2)
        self.label_statusbar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_statusbar.setObjectName("label_statusbar")
        self.pushButton_help = QtWidgets.QPushButton(self.splitter_2)
        self.pushButton_help.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_help.setFont(font)
        self.pushButton_help.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.pushButton_help.setObjectName("pushButton_help")
        self.splitter_3 = QtWidgets.QSplitter(Form)
        self.splitter_3.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_4 = QtWidgets.QSplitter(Form)
        self.splitter_4.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")

        self.retranslateUi(Form)
        self.pushButton_StartTour.clicked.connect(self.click_StartTour)
        self.pushButton_PauseTour.clicked.connect(self.click_PauseTour)
        self.pushButton_ResumeTour.clicked.connect(self.click_ResumeTour)
        self.pushButton_EndTour.clicked.connect(self.click_EndTour)
        self.pushButton_GoGoal.clicked.connect(self.click_Go)
        self.pushButton_CancelGoal.clicked.connect(self.click_Cancel)
        self.pushButton_help.clicked.connect(self.click_Help)
        self.comboBox_GoalSelect.activated['QString'].connect(self.onActivated)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_7.setText(_translate("Form", "Tour tự động"))
        self.pushButton_StartTour.setText(_translate("Form", "Bắt đầu"))
        self.pushButton_PauseTour.setText(_translate("Form", "Tạm dừng"))
        self.pushButton_ResumeTour.setText(_translate("Form", "Tiếp tục"))
        self.pushButton_EndTour.setText(_translate("Form", "Kết thúc"))
        self.pushButton_GoGoal.setText(_translate("Form", "Đi"))
        self.pushButton_CancelGoal.setText(_translate("Form", "Hủy"))
        self.comboBox_GoalSelect.setCurrentText(_translate("Form", "Home"))
        self.label_6.setText(_translate("Form", "Lựa chọn điểm đến"))
        self.label_GoalDetail.setText(_translate("Form", "Mô tả"))
        self.label_8.setText(_translate("Form", "Thông tin"))
        self.label_3.setText(_translate("Form", "Điểm hiện tại:"))
        self.label_4.setText(_translate("Form", "Điểm tiếp theo:"))
        self.label_5.setText(_translate("Form", "Mức pin:"))
        self.label_9.setText(_translate("Form", "Camera"))
        self.label_CameraView.setText(_translate("Form", "image camera"))
        self.label.setText(_translate("Form", "AGV-HUST"))
        self.label_statusbar.setText(_translate("Form", "Status bar..."))
        self.pushButton_help.setText(_translate("Form", "Hướng dẫn"))

    @pyqtSlot()
    def click_StartTour(self):
        pass
    @pyqtSlot()
    def click_PauseTour(self):
        pass
    @pyqtSlot()
    def click_ResumeTour(self):
        pass
    @pyqtSlot()
    def click_EndTour(self):
        pass
    @pyqtSlot()
    def click_Go(self):
        pass
    @pyqtSlot()
    def click_Cancel(self):
        pass
    @pyqtSlot()
    def click_Help(self):
        pass
    @pyqtSlot()
    def onActivated(self):
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

